#!/bin/bash

starting_dir=${1}/${2}
project_name=${2}

tmux rename-window editor
tmux send-keys -t $project_name:1 'vim' C-m

tmux new-window -t $project_name -c $starting_dir -n console

tmux select-window -t $project_name:1
