#! /bin/sh

### Clean Up
bspc rule -r "*"
killall "sxhkd"
killall "picom"
killall "nitrogen"

### Autostart
sxhkd &
feh --no-fehbg --bg-scale '/home/joe/Pictures/Wallpapers/road-marking-trees.jpg'
$HOME/.config/polybar/launch.sh $HOME/.config/polybar/forest-theme
picom --vsync --backend glx &

### Monitors
bspc monitor DisplayPort-0 -d web code chat gaming settings
bspc monitor DisplayPort-1 -d tv docs
### BSPWM Configuration
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config focused_border_color "#FDFDFF"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Postman desktop='web' follow=on
bspc rule -a jetbrains-idea-ce desktop='code' follow=on
bspc rule -a discord desktop='chat' follow=on
bspc rule -a Signal desktop='chat' follow=on
bspc rule -a zoom desktop='chat' follow=on
bspc rule -a Lutris desktop='gaming' follow=on
bspc rule -a Nitrogen desktop='settings' follow=on
bspc rule -a Pcmanfm desktop='settings' follow=on
bspc rule -a Piper desktop='settings' follow=on
bspc rule -a org.gnome.DejaDup desktop='settings' follow=on
bspc rule -a Buttercup desktop='settings' follow=on
