#!/bin/bash

starting_dir=$(pwd)
project_name=$(basename $(pwd))

tmux new -s $project_name -d
tmux rename-window editor
tmux send-keys -t $project_name:1 'vim' C-m

tmux new-window -t $project_name -c $starting_dir -n console

tmux select-window -t $project_name:1
