#!/bin/bash

spec_dir=$(pwd)/src/main/resources/spec

tmux rename-window editor
tmux send-keys -t 1 'nvim' C-m
tmux split-window -v -l 30% -t 1

tmux new-window -c $spec_dir -n docs
tmux send-keys -t 2.1 'nvim ' $spec_dir/openapi.yaml C-m
tmux split-window -t -c $spec_dir -v -p 20
tmux send-keys -t 2.2 'openapi lint openapi.yaml' C-m
tmux split-window -t $project_name -c $spec_dir -h -p 50
tmux send-keys -t 2.3 'openapi preview-docs openapi.yaml'
tmux select-pane -t 2.1

tmux select-window -t 1
tmux select-pane -t 1
