#!/bin/bash

starting_dir=$(pwd)
project_name=$(basename $(pwd))
spec_dir=$starting_dir/src/main/resources/spec

tmux rename-session $project_name
tmux rename-window -t $project_name editor
tmux send-keys -t $project_name:1 'vim' C-m
tmux split-window -v -l 30% -t $project_name:1

tmux new-window -t $project_name -c $spec_dir -n docs
tmux send-keys -t $project_name:2.1 'vim ' $spec_dir/openapi.yaml C-m
tmux split-window -t $project_name -c $spec_dir -v -p 20
tmux send-keys -t $project_name:2.2 'openapi lint openapi.yaml' C-m
tmux split-window -t $project_name -c $spec_dir -h -p 50
tmux send-keys -t $project_name:2.3 'openapi preview-docs openapi.yaml'
tmux select-pane -t $project_name:2.1

tmux select-window -t $project_name:1
tmux select-pane -t 1
