#!/bin/bash

set -eo pipefail
starting_directory=$(
    cd ~ && find . ~/Repos -mindepth 1 -maxdepth 1 -type d -print | \
    fzf | \
    xargs -I directory realpath directory 2>/dev/null)
tmux new -c $starting_directory
clear
