#!/usr/bin/sh

config_dir=~/.config
theme_file_paths=(
    $config_dir/bspwm/bspwmrc
    $config_dir/rofi/config.rasi
    $config_dir/alacritty/alacritty.yml
)

function get_themes() {
    echo "forest"
    echo "dr stone"
    echo "simp"
}

function update_wallpaper() {
    sed -i -E "11 s/(\/([a-zA-Z0-9]+-.[^\/\.]+)+)/\/$1/" ${theme_file_paths[0]}
}

function update_polybar_theme() {
    sed -i -E "12 s/(([a-zA-Z0-9]+-.[^\/\.]+)+)/$1/" ${theme_file_paths[0]}
}

function update_rofi_theme() {
    sed -i -E "5 s/(([a-zA-Z0-9]+-.[^\/\.]+)+)/$1/" ${theme_file_paths[1]}
}

function update_alacritty_theme() {
    sed -i -E "265 s/(([a-zA-Z0-9]+-.[^\/\.]+)+)/$1/" ${theme_file_paths[2]}
}

selected_theme=$( get_themes | rofi -dmenu -i -p "theme select" )

case "$selected_theme" in
    "forest")
        update_wallpaper 'road-marking-trees'
        update_polybar_theme 'forest-theme'
        update_rofi_theme 'forest-theme'
        update_alacritty_theme 'forest-theme'
        ;;
    "dr stone")
        update_wallpaper 'young-senku'
        update_polybar_theme 'dr-stone-theme'
        update_rofi_theme 'dr-stone-theme'
        update_alacritty_theme 'dr-stone-theme'
        ;;
    "simp")
        update_wallpaper 'my-dress-up-darling'
        update_polybar_theme 'dr-stone-theme'
        update_rofi_theme 'dr-stone-theme'
        update_alacritty_theme 'my-dress-up-darling'
        ;;
    *)
        ;;
esac

bspc wm -r
