#!/usr/bin/sh

get_options() {
	echo "left"
	echo "right"
	echo "both"
}

choice=$( get_options | rofi -dmenu -i -p "select" )

reset_defaults() {
        #echo 'awesome.restart()' | awesome-client 2> /dev/null
        bspc wm -r
}

move_input_sinks_to_viotek_monitor_with_sound() {
    pactl set-card-profile alsa_card.pci-0000_0a_00.1 output:hdmi-stereo-extra4
    hdmi_5_card_sink=$(pactl list short sinks | sed -n '/alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra4/p' | cut -f 1)
    sink_inputs=$(pactl list short sink-inputs | cut -f 1)

    for sink_input in sink_inputs; do
        pactl move-sink-input $sink_input $hdmi_5_card_sink
    done
}

case "$choice" in
    "left")
        xrandr --output DisplayPort-1 --mode 3840x2160 --rate 60.00 --primary --dpi DisplayPort-1 --output DisplayPort-0 --off
	reset_defaults
	;;
    "right")
        xrandr --output DisplayPort-0 --mode 1920x1080 --rate 143.98 --primary --dpi DisplayPort-0 --output DisplayPort-1 --off
	reset_defaults
    	;;
    "both")
        xrandr --output DisplayPort-0 --mode 1920x1080 --rate 143.98 --primary --dpi DisplayPort-0 --output DisplayPort-1 --mode 3840x2160 --rate 60.00 --left-of DisplayPort-0
        move_input_sinks_to_viotek_monitor_with_sound
	reset_defaults
    	;;
    *)
    	echo "Invalid choice selected: $choice"
    	;;
esac
