theme = "gruvbox_dark_soft"

[editor]
auto-pairs = false
line-number = "relative"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["position", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
other-lines = "error"
